name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Build
        run: npm run build
      - name: Run test
        run: npm run start
        env:
          EXECUTABLE_PATH: /usr/bin/google-chrome-stable
