name: Test environment variables

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "CUSTOM_ENV=test" >> $GITHUB_ENV;
      - name: Log env
        run: echo $CUSTOM_ENV;
