name: Test environment variables

on:
  workflow_dispatch:
    inputs:
      test1:
        description: "test1"
        required: true
      test2:
        description: "test2"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Log inputs
        run: |
          echo ${{ github.event.inputs.test1 }};
          echo ${{ github.event.inputs.test2 }};
      - name: Log inputs with setting env
        run: |
          echo ${TEST1};
          echo ${TEST2};
        env:
          TEST1: ${{ github.event.inputs.test1 }}
          TEST2: ${{ github.event.inputs.test2 }}
